### ISSUE TITLE
Testar integração do Front-end com  Back-end

### ISSUE THREAD

**Issue by Ruan-Franklin** [tads-cnat/gameprofile#118]
**Tempo previsto (em horas):Alta**

**Tempo gasto (em horas):**

**Complexidade (baixa | média | alta):Alta**

**Qualidade (baixa | média | alta):Alta**

**Descrição**

É importante testar a integração do back-end e front-end do projeto na branch *dev*, visto que há um trabalho para deixar a branch *main* como a principal branch do projeto,, e no momento a branch *dev* é a mais atualizada e importante no momento.

**Comment by dinapgomes** [comment]
Integração do back-end com o front-end testada e funcionando corretamente.
