### ISSUE TITLE
Cronograma de marcos

### ISSUE THREAD

**Issue by dinapgomes** [tads-cnat/gameprofile#82]
**Tempo previsto (em horas): 6**

**Tempo gasto (em horas):**

**Complexidade (baixa | média | alta): média **

**Qualidade (baixa | média | alta): alta**

**Descrição**
É necessário adicionar ao cronograma de marcos as etapas mais importantes dos PDS Web e Corporativo

**Comment by Franklin-Barbosa** [comment]
Cronograma de Marcos inicial: [Cronograma de Macos - GameProfile.xlsx](https://github.com/tads-cnat/gameprofile/files/11526001/Cronograma.de.Macos.-.GameProfile.xlsx)
